# aarch64-apple-darwin
# arm-unknown-linux-gnueabihf
# armv7-unknown-linux-musleabihf
# x86_64-pc-windows-gnu
# x86_64-unknown-linux-gnux32
# x86_64-unknown-linux-musl

[alias]
mac-check   = "check --target aarch64-apple-darwin --all-targets"
win-check   = "check --target x86_64-pc-windows-gnu --all-targets"
linux-check = "check --target arm-unknown-linux-gnueabihf --all-targets"
