name: Pull request
# This workflow is triggered on pushes to the repository.
on: [ pull_request ]

jobs:
  check:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # A PR should not contain too many commits
          fetch-depth: 10
      - name: Validate commit messages
        run: |
          git show-ref
          curl -sSfL https://github.com/convco/convco/releases/download/v0.6.4/convco-ubuntu.zip -o convco-ubuntu.zip
          echo "d6e43a1975949ef05d31bb1ac64fdd7c2dbc18b0b65df075c16dc296b8153be7  convco-ubuntu.zip" | sha256sum -c
          zcat convco-ubuntu.zip > convco
          chmod +x convco
          ./convco check ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
          rm convco convco-ubuntu.zip

  check_fmt:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: cargo-fmt
        run: cargo fmt --all --check


